# Generated by Django 2.1.1 on 2018-09-15 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagegen', '0004_auto_20180915_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='viewed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
