# Generated by Django 2.1.1 on 2018-09-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagegen', '0005_auto_20180915_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
